-- This file is generated by database/python/main.py.
-- Its purpose is to collect all queries/commands into a single file that can be executed by Professor Yerkes with less trouble than running them individually.
-- The create, delete, and update scripts were all written manually by me (Reece) and copied in while the insert statements were auto-generated in `model.py`. 

-- Reece McMillin, CS470, 2022-05-02

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Drop and recreate database

DROP DATABASE IF EXISTS `bloodbank`;
CREATE DATABASE `bloodbank`;

-- Drop existing tables

USE bloodbank;

SET
    foreign_key_checks = 0;

DROP TABLE IF EXISTS client;

DROP TABLE IF EXISTS blood_donation;

DROP TABLE IF EXISTS blood_transfusion;

DROP TABLE IF EXISTS blood_bank;

DROP TABLE IF EXISTS blood_bank_employee;

DROP TABLE IF EXISTS hospital;

DROP TABLE IF EXISTS hospital_employee;

SET
    foreign_key_checks = 1;

-- Create the tables, stored procedures, and views (if any) in order.

USE bloodbank;

CREATE TABLE IF NOT EXISTS client (
    ClientId INTEGER PRIMARY KEY AUTO_INCREMENT,
    FullName TEXT NOT NULL,
    BloodType TEXT NOT NULL,
    EmailAddress VARCHAR(255) UNIQUE NOT NULL,
    HomeAddress TEXT NOT NULL,
    DateOfBirth TEXT NOT NULL,
    PhoneNumber TEXT NOT NULL,
    PasswordSalt TEXT NOT NULL,
    PasswordHash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS blood_bank (
    BloodBankId INTEGER PRIMARY KEY AUTO_INCREMENT,
    ManagerId INTEGER UNIQUE NOT NULL,
    StreetAddress VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS blood_bank_employee (
    EmployeeId INTEGER AUTO_INCREMENT,
    EmployerId INTEGER NOT NULL,
    FullName VARCHAR(255) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Ssn INTEGER NOT NULL,
    PasswordSalt TEXT NOT NULL,
    PasswordHash TEXT NOT NULL,
    HomeAddress VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    PRIMARY KEY (EmployeeId)
);

CREATE TABLE IF NOT EXISTS hospital (
    HospitalId INTEGER PRIMARY KEY AUTO_INCREMENT,
    HospitalName VARCHAR(80) NOT NULL,
    StreetAddress TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hospital_employee (
    EmployeeId INTEGER PRIMARY KEY AUTO_INCREMENT,
    EmployerId INTEGER NOT NULL,
    FullName VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS blood_transfusion (
    TransfusionId INTEGER PRIMARY KEY AUTO_INCREMENT,
    EmployeeId INTEGER NOT NULL,
    TransfusionDate DATE NOT NULL,
    Amount INTEGER NOT NULL,
    RecipientId INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS blood_donation (
    DonationId INTEGER PRIMARY KEY AUTO_INCREMENT,
    EmployeeId INTEGER NOT NULL,
    DonorId INTEGER NOT NULL,
    ScreenResult TEXT NOT NULL,
    DonationDate DATE NOT NULL,
    Amount INTEGER NOT NULL
);

DELIMITER //

CREATE PROCEDURE `sp_GetTotalDonatedByClientId`(IN id INT)
BEGIN
    SELECT SUM(Amount)
    FROM blood_donation
    GROUP BY DonorId
    HAVING DonorId = id;
END //

CREATE PROCEDURE `sp_GetTotalReceivedByClientId`(IN id INT)
BEGIN
    SELECT SUM(Amount)
    FROM blood_transfusion
    GROUP BY RecipientId
    HAVING RecipientId = id;
END //

DELIMITER ;

CREATE VIEW v_GetClientWithDonations AS
SELECT
    *
FROM
    client
    JOIN blood_donation ON client.ClientId = blood_donation.DonorId;

CREATE VIEW v_GetClientWithTransfusions AS
SELECT
    *
FROM
    client
    JOIN blood_transfusion ON client.ClientId = blood_transfusion.RecipientId;

-- The next one is a little quirky and probably won't produce anything, I found an issue with my fake data generation that I'm still working out!
-- It'll be fully resolved before the due date.

CREATE VIEW v_BloodBankManagers AS
SELECT
    *
FROM
    blood_bank_employee
    JOIN blood_bank ON blood_bank_employee.EmployeeId = blood_bank.ManagerId
    AND blood_bank_employee.EmployerId = blood_bank.BloodBankId;


-- Insert Reece's auto-generated data

INSERT INTO client (FullName, BloodType, EmailAddress, HomeAddress, DateOfBirth, PhoneNumber, PasswordSalt, PasswordHash) VALUES
	('Mesha Wallace', 'A+', 'Mesha Wallace@gmail.com', '156 E Ainsworth', '1973-04-23', '502-129-5512', '$2b$04$jDs6LuJVMKOjKV2NDvfgb.', '$2b$04$jDs6LuJVMKOjKV2NDvfgb.nAAd.8GtzKjxtWQvp0Rw1zl7FmgEz3K'),
	('Stepanie Briggs', 'B+', 'Stepanie Briggs@gmail.com', '554 N Dellwood', '1963-10-27', '898-781-1380', '$2b$04$cZLbKaK36LFnzAKoFpa0s.', '$2b$04$cZLbKaK36LFnzAKoFpa0s.wJR6VEc7cWPbvQHxBNSs4Ie1aCCgQVq'),
	('Dominika Ashley', 'B+', 'Dominika Ashley@gmail.com', '575 W Woodridge', '1981-12-07', '585-847-4002', '$2b$04$JTwskgzbDD14dR/F4Bjywe', '$2b$04$JTwskgzbDD14dR/F4BjywePMbBsMSmRfKa55m8JHf3ITXQDdpY5Qu'),
	('Jeanice Moser', 'AB+', 'Jeanice Moser@gmail.com', '884 E Panoha', '1994-02-20', '702-384-7478', '$2b$04$k3T2NLG9jyOiYamO7aIKOO', '$2b$04$k3T2NLG9jyOiYamO7aIKOOYuAU5Tcz38X6xwdkJqHMps4ZFjhg7WO'),
	('Christella Simon', 'A+', 'Christella Simon@gmail.com', '380 W Blackhaw', '1947-11-09', '993-537-2367', '$2b$04$DsGNcMdgW0Ko7175yd/iu.', '$2b$04$DsGNcMdgW0Ko7175yd/iu.fdxBO2pNsWMk.RNwNjMlRQd4XAZHWu6'),
	('Dorell Craven', 'AB+', 'Dorell Craven@gmail.com', '710 N Pinesap', '1957-12-08', '781-522-6357', '$2b$04$hvX/CDv.t5FbTOelD17/wO', '$2b$04$hvX/CDv.t5FbTOelD17/wO2C.W5uJ6H1uNwMAsSC5pYxH/EoRHzRi'),
	('Dynisha Lewis', 'O-', 'Dynisha Lewis@gmail.com', '198 W Anchorage', '1979-07-02', '683-806-9861', '$2b$04$Bs8drClUx0gxxPlIkeTi5.', '$2b$04$Bs8drClUx0gxxPlIkeTi5.WT4xzUHEdcflitwfLVOfdeJaI6Uqyaq'),
	('Alichia Kelly', 'AB-', 'Alichia Kelly@gmail.com', '333 E Industrial', '1949-07-28', '499-904-1091', '$2b$04$DMS47QsK8gVKc89Z73rJie', '$2b$04$DMS47QsK8gVKc89Z73rJieJ1tIi.Qi5QxNIJZ0fmevZ6akLRAnZz2'),
	('Zipporah Gould', 'A-', 'Zipporah Gould@gmail.com', '240 E Grasshopper', '1936-06-03', '771-995-9731', '$2b$04$BVrdU1YkXisMd39ZAqJEVe', '$2b$04$BVrdU1YkXisMd39ZAqJEVeOPWhY.BBWSm2BAFHRNc8etxjjWob0M.'),
	('Tiffani Dudley', 'O-', 'Tiffani Dudley@gmail.com', '815 S Regentview', '1987-09-08', '802-359-8933', '$2b$04$ULcSISRIwCjutwvIe.Bpm.', '$2b$04$ULcSISRIwCjutwvIe.Bpm.k3aGnbXfCLpj8ku8qp8zEFm1/X.Tp1S'),
	('Tysheka Parrott', 'O+', 'Tysheka Parrott@gmail.com', '902 W Thornbrook', '1956-01-02', '538-688-9702', '$2b$04$rrVaNf6IJ9wWxibp6eQ0Ve', '$2b$04$rrVaNf6IJ9wWxibp6eQ0VeVVVMgdzKGm1LBgJoRHtSjEfNAlb1KJa'),
	('Mrk Batchelor', 'O-', 'Mrk Batchelor@gmail.com', '818 S Bubbling Brook', '1943-05-23', '684-148-2195', '$2b$04$b7q7dPm/0tfcLQxviyyyBe', '$2b$04$b7q7dPm/0tfcLQxviyyyBezuv6uK/8nxoovYEjZo8OxCtW7oZW9be'),
	('Evamarie Pollard', 'B-', 'Evamarie Pollard@gmail.com', '700 N Mendel', '1937-09-26', '627-261-7531', '$2b$04$nuNj7ZzSTCfEO6mnoalNNe', '$2b$04$nuNj7ZzSTCfEO6mnoalNNegz6UkKmWQZNbBjQTnfxWJErjPRIRSdC'),
	('Orly Bland', 'B-', 'Orly Bland@gmail.com', '781 N Fischer', '1984-09-14', '568-297-2563', '$2b$04$b4jO7XM94Mn4BS4Pr5V3hu', '$2b$04$b4jO7XM94Mn4BS4Pr5V3huBvCR/C8Ce/uB1d.47ZFqs9sTML/CMYC'),
	('Dolan Kim', 'AB-', 'Dolan Kim@gmail.com', '575 E Malcolm', '1977-05-22', '821-492-3218', '$2b$04$1.QzBXMX1znAQJ.nx8x1qO', '$2b$04$1.QzBXMX1znAQJ.nx8x1qO3/l9lmp4ets4kMYlYpML9KvV8KG76LK'),
	('Lenia Kent', 'AB-', 'Lenia Kent@gmail.com', '3 N Apahon', '1965-07-25', '611-464-9303', '$2b$04$1uQ5VcUTzgum7BP8lhMbp.', '$2b$04$1uQ5VcUTzgum7BP8lhMbp.Fp0OX6wK1NgTkLVEjeVa3yAWWZTlaHW'),
	('Fulton Robinson', 'B+', 'Fulton Robinson@gmail.com', '551 W Oasis', '1996-06-10', '698-438-1819', '$2b$04$gVUbULQj4HxGvoZSs/bXNe', '$2b$04$gVUbULQj4HxGvoZSs/bXNenJIrLAe9ySkb.zEe4z7I.anpgEDuL6m'),
	('Louvenia Connor', 'AB-', 'Louvenia Connor@gmail.com', '400 W Mustang', '1953-01-21', '721-395-7006', '$2b$04$xDDPWnEecxf5TezKko7dle', '$2b$04$xDDPWnEecxf5TezKko7dletCZro9lsfEgQN2sI/1hhUL0fkifULLq'),
	('Kimberlyann Swanson', 'O+', 'Kimberlyann Swanson@gmail.com', '522 E Alchester', '1947-01-05', '152-599-1025', '$2b$04$fvJVehfpzAXJDAYcUJPcmu', '$2b$04$fvJVehfpzAXJDAYcUJPcmu/l5b6JBng4PmDjDxxEoz7bt2IWnut9e'),
	('Serita Parrott', 'O+', 'Serita Parrott@gmail.com', '855 E Branford', '1952-09-21', '101-418-4696', '$2b$04$8PdOt5nws6N3RGtjFWiyrO', '$2b$04$8PdOt5nws6N3RGtjFWiyrOgIOBKuPoDScu4PY5yvVJ.3beLJLl5Fa'),
	('Lewis Byrne', 'O-', 'Lewis Byrne@gmail.com', '650 E Arcola', '1970-09-18', '901-970-1639', '$2b$04$1ZDJi9DB0P0Ui5tEjd/Lf.', '$2b$04$1ZDJi9DB0P0Ui5tEjd/Lf.AYpQ.k47Yw2z1zLGJVl7odp3b8SEYu6'),
	('Martina Gold', 'A+', 'Martina Gold@gmail.com', '269 N Ramsey', '1997-04-17', '266-306-1797', '$2b$04$V/dJlnzhQzyrmrUCPfjOce', '$2b$04$V/dJlnzhQzyrmrUCPfjOces5gBlrrvWdYrSD8FIYkQ/CPoGZYC.hO'),
	('Kaetlyn Harrell', 'B+', 'Kaetlyn Harrell@gmail.com', '308 N Pawnee Avenue', '1997-09-11', '822-684-9474', '$2b$04$JhwQFpGtBKxsG19qQQiKj.', '$2b$04$JhwQFpGtBKxsG19qQQiKj.VKYmtWAQW3GLxOrjflofgoa0n6xPFYi'),
	('Gala Crane', 'A+', 'Gala Crane@gmail.com', '751 E Elm Leaf', '1979-05-14', '636-871-5835', '$2b$04$4xUFKTXYWFYdgjqGLCYrMu', '$2b$04$4xUFKTXYWFYdgjqGLCYrMur8DPse5qSonFaxa9ESth1wF2JEfxv0u'),
	('Nicky Cole', 'B-', 'Nicky Cole@gmail.com', '70 S Nikerton', '1961-11-18', '919-717-4933', '$2b$04$TUXLnVgRpmKqf27htrOg0.', '$2b$04$TUXLnVgRpmKqf27htrOg0.H2lLSlxt7Z5b.HnWv8ZpAwfVjQUxi7q'),
	('Kiele Marks', 'A+', 'Kiele Marks@gmail.com', '493 E West', '1998-08-28', '966-398-7884', '$2b$04$mnaVFb/at0XnVs7gesZcM.', '$2b$04$mnaVFb/at0XnVs7gesZcM.SPvhXcysUbh3gLfQv7bTEwGSw24gOZW'),
	('Ramin Alford', 'AB-', 'Ramin Alford@gmail.com', '114 E Malabar', '1982-02-17', '716-397-1468', '$2b$04$KgY9lidBMgvbDAd5FWJcYO', '$2b$04$KgY9lidBMgvbDAd5FWJcYOC1Nc.M/Kz7lPMkPt4Tuj7qfznEyQggm'),
	('Shonelle Lee', 'O+', 'Shonelle Lee@gmail.com', '156 E Perthshire', '1966-01-22', '290-857-5751', '$2b$04$BLxsno3YWmlgWXPmj9FnO.', '$2b$04$BLxsno3YWmlgWXPmj9FnO.P22zkTVPyM3pjJEwRx04iDPQ2fNBJXm'),
	('Shamela Hinson', 'O-', 'Shamela Hinson@gmail.com', '980 E Sparkling Lake', '1960-02-15', '373-988-7686', '$2b$04$a03FWFOfVUfFU.CtgjT3aO', '$2b$04$a03FWFOfVUfFU.CtgjT3aOA.4xr0tzvCtgdCBmWb2XEEmQrmv3A42'),
	('Kelita Bates', 'A+', 'Kelita Bates@gmail.com', '40 W Cedar Lake', '1993-06-13', '872-894-9280', '$2b$04$Ps59OXczqNxGQBHkk4OLUe', '$2b$04$Ps59OXczqNxGQBHkk4OLUe.rKEwsq/ZQ0POPziasRmkoGofaZIurG'),
	('Donnavan Boyle', 'A+', 'Donnavan Boyle@gmail.com', '960 S Oriole', '1989-09-01', '740-382-2588', '$2b$04$2gtT8G8DGywq.E3sGEeCve', '$2b$04$2gtT8G8DGywq.E3sGEeCveSyhM8s9X9L5yD8FI5wY5ChqEJhiyt22'),
	('Anda Dixon', 'B-', 'Anda Dixon@gmail.com', '489 S Ashbrook', '1979-04-05', '497-608-6534', '$2b$04$LpjSwOWwcg8xt5uAu5tyRe', '$2b$04$LpjSwOWwcg8xt5uAu5tyReiI4V5zkpvrlfh5CocTGQ/WAHEkXn.iG'),
	('Kyoko Robertson', 'AB+', 'Kyoko Robertson@gmail.com', '882 E Pangbourne', '1991-06-28', '670-316-9042', '$2b$04$4.orbFzUVOImJnkCLWmu6u', '$2b$04$4.orbFzUVOImJnkCLWmu6u64TgrCygbnPYdtalxnOTi5TTIEf3n2W'),
	('Glinda Lane', 'A+', 'Glinda Lane@gmail.com', '108 N Ramblewood', '1941-06-16', '556-996-7989', '$2b$04$3JKKi71RNxv.qpKOfm7MQO', '$2b$04$3JKKi71RNxv.qpKOfm7MQOqjy.vUcl/eB/ATWBWtYptNUmWTWnmia'),
	('Dayanna Hood', 'A-', 'Dayanna Hood@gmail.com', '850 N Chadbourne', '1969-01-05', '528-121-3352', '$2b$04$mShukyAdC3xLPSEoVg5cMO', '$2b$04$mShukyAdC3xLPSEoVg5cMO8EKN7n5KUP.h/TjqwdAOasqSuCeEK9.'),
	('Aaron Cameron', 'A+', 'Aaron Cameron@gmail.com', '534 S Brenley', '1931-01-12', '537-935-6712', '$2b$04$Xjp10TqxDYHdJ77ef.s5WO', '$2b$04$Xjp10TqxDYHdJ77ef.s5WOKvqFG3s.oKgC8CNA0XwfWi0757kJwH2'),
	('Jacoby Bartlett', 'A+', 'Jacoby Bartlett@gmail.com', '279 W Hayden', '1978-05-10', '582-837-8100', '$2b$04$RwE0pwrv6K3j7P0ESSizG.', '$2b$04$RwE0pwrv6K3j7P0ESSizG.RN0p6woTnGD31DYDXYgLddbGsl/sPzm'),
	('Emilio Kang', 'AB+', 'Emilio Kang@gmail.com', '305 S Poplar', '1947-06-25', '379-900-6302', '$2b$04$SGJeoSulcxhCKJ8dX3v9ne', '$2b$04$SGJeoSulcxhCKJ8dX3v9newynIgCdXnCY4zreAm2T5mdwPQ4WBCey'),
	('Landy Cowan', 'AB+', 'Landy Cowan@gmail.com', '805 S Deer Path', '1951-11-25', '390-997-1894', '$2b$04$zHuBVT.MfqjmtdpEZOViw.', '$2b$04$zHuBVT.MfqjmtdpEZOViw.jgm.fa1FTn3VsWgtaBVUK8jNFpBhD2u'),
	('Catherin Boyette', 'O-', 'Catherin Boyette@gmail.com', '680 N Cross Pike', '1941-06-26', '336-648-3635', '$2b$04$3EmqHGWrgpTl3LRmWQnh1u', '$2b$04$3EmqHGWrgpTl3LRmWQnh1uR4MSCqF13Pznq0BWgj/HnrBO4y4gZxu'),
	('Tanara Herring', 'O+', 'Tanara Herring@gmail.com', '42 W Carnelian', '1995-01-16', '698-802-7448', '$2b$04$D1JKmG2WLj9CkwSOKyidOe', '$2b$04$D1JKmG2WLj9CkwSOKyidOeFthbs7Y/oWOrdVLXhZ8IQ8/U9bJ0r1m'),
	('Shantiel Werner', 'O+', 'Shantiel Werner@gmail.com', '7 N Moonlight Bay', '1991-08-08', '110-785-9131', '$2b$04$7ZsoVU2zxGZCLbzNwToKSO', '$2b$04$7ZsoVU2zxGZCLbzNwToKSOk1wI6JHp6VRoqxT/BAKMdwJyhIAg1qe'),
	('Neng Moran', 'A+', 'Neng Moran@gmail.com', '896 E Oxford', '1944-09-22', '478-654-6965', '$2b$04$zgubhpWY6YIS/sS6BwbKiO', '$2b$04$zgubhpWY6YIS/sS6BwbKiO9QOc90Bz5WX8xz34Di94X7QzuKUnKUC'),
	('Lawerence Weber', 'AB+', 'Lawerence Weber@gmail.com', '67 N Eversholt', '1974-07-07', '639-457-8982', '$2b$04$VXWcv/zp5X8uBaTX9nSEmu', '$2b$04$VXWcv/zp5X8uBaTX9nSEmuM1iDgTgsy.WNUlDr9M.wJ73aaEBK//S'),
	('Mairin West', 'B+', 'Mairin West@gmail.com', '731 N Circle Trees', '1964-10-21', '358-633-2587', '$2b$04$r2sPElP9rT8wovCam2GhtO', '$2b$04$r2sPElP9rT8wovCam2GhtOpnsHhDYYCletd.69ziiEgOB83mq3FCO'),
	('Wiliam Lamb', 'A+', 'Wiliam Lamb@gmail.com', '722 S Dallager', '1939-12-03', '124-346-8768', '$2b$04$Q2oqb7kVP29zEIej/K1dHe', '$2b$04$Q2oqb7kVP29zEIej/K1dHeyXxXFCgYcrcZ7rWX6qGCY764tfX8VXe'),
	('Angelo Stark', 'O+', 'Angelo Stark@gmail.com', '715 S Laurie', '1957-12-28', '700-151-4736', '$2b$04$mOSXMnJJZNsLI/W.lk30Cu', '$2b$04$mOSXMnJJZNsLI/W.lk30Cu0qxqpNPo9eoMFL.YpY8qNXVN1NhDQVa'),
	('Skipper Fischer', 'AB-', 'Skipper Fischer@gmail.com', '582 W Tanya', '1976-03-11', '650-607-1354', '$2b$04$qAsU63jDBcW94fxiovIdqO', '$2b$04$qAsU63jDBcW94fxiovIdqOb4/dE75o07DJkAe1DuyZZwFjtk2kxlu'),
	('Cleo Beard', 'B-', 'Cleo Beard@gmail.com', '890 W Sandy Berry', '1963-12-23', '534-472-8864', '$2b$04$T6xyF3Hab8MbAl6Emti3se', '$2b$04$T6xyF3Hab8MbAl6Emti3sewYuWNB1QXMXHcZ.ZibexX3KfZBtsmAK'),
	('Nashay Ellington', 'B+', 'Nashay Ellington@gmail.com', '212 W Wolf River', '1993-11-18', '479-520-1710', '$2b$04$EajXOXA6FTN2FibarKSdl.', '$2b$04$EajXOXA6FTN2FibarKSdl.ioMnkAB1SEh..7DgK9hNys.ZBEnEXgm'),
	('Brigett Christensen', 'A+', 'Brigett Christensen@gmail.com', '685 S Whitemarsh', '1930-01-13', '890-219-7999', '$2b$04$IdEcX5ndaZqhzsUuGiR.Ne', '$2b$04$IdEcX5ndaZqhzsUuGiR.NewcI4Ktz8tH1z/ymbvygYaC9pgZ9FR7u'),
	('Jennifier Noble', 'B-', 'Jennifier Noble@gmail.com', '271 S Winding Creek', '1936-01-04', '805-234-6167', '$2b$04$LTyMvSwFfLdQy1TNucP0pu', '$2b$04$LTyMvSwFfLdQy1TNucP0puek3qhDsvflkmFGgQSmACk3glFlP9WOW'),
	('Stephanye White', 'B-', 'Stephanye White@gmail.com', '410 W Memorial', '1962-10-23', '330-536-4935', '$2b$04$bEjQAIe50HquDaEKXqyFpO', '$2b$04$bEjQAIe50HquDaEKXqyFpOR4LlrlDGU0ZCH5Pn4R0jPohkADnFB2y'),
	('Smauel Tan', 'O-', 'Smauel Tan@gmail.com', '847 E Knoll', '1952-08-09', '710-762-6303', '$2b$04$sS/636mCGP2teYLbtd5KCO', '$2b$04$sS/636mCGP2teYLbtd5KCOfkJ9v2BwxN9MIn05yjDEKHmrnLjrMRG'),
	('Nikhil Marcus', 'O-', 'Nikhil Marcus@gmail.com', '646 N Ashbrook', '1961-12-05', '828-260-9012', '$2b$04$mFkkpumVpG6KFBrKuFGhaO', '$2b$04$mFkkpumVpG6KFBrKuFGhaOyDrdSaL2olpZDonLM9qaan.xxNUbJRe'),
	('Chessa Jernigan', 'B+', 'Chessa Jernigan@gmail.com', '561 N Anniston', '1937-07-22', '476-655-4726', '$2b$04$BJzRevD0Psg3b3VIexlSz.', '$2b$04$BJzRevD0Psg3b3VIexlSz.7EE85kh1bGVP2Z2MJ2YawGgQRONQa6q'),
	('Valine Horn', 'O+', 'Valine Horn@gmail.com', '875 E Trowbridge', '1947-03-23', '826-303-7011', '$2b$04$NmevjYmw8pIjnhTSsFgpJu', '$2b$04$NmevjYmw8pIjnhTSsFgpJu.yUGfcKCf.y8fvwG4a41FiE0EFYWIV2'),
	('Latravis Greer', 'A+', 'Latravis Greer@gmail.com', '999 S Lakespur', '1948-02-25', '766-492-8815', '$2b$04$hLOLw.yNjSmo4rBkO4ELku', '$2b$04$hLOLw.yNjSmo4rBkO4ELkuGk4Rn9mSTOM0vrOOq8EpgSF1NZ8N3rK'),
	('Lyndse Becker', 'A+', 'Lyndse Becker@gmail.com', '301 S Old Deer', '1944-06-19', '248-561-3528', '$2b$04$5yLx2ZZ1oAR0r87vwfXKGO', '$2b$04$5yLx2ZZ1oAR0r87vwfXKGOFSOvaqmd6SthK7mvNg.SkFS7StS6t4m'),
	('Taira Weeks', 'A+', 'Taira Weeks@gmail.com', '255 E Danforth', '1964-11-23', '430-981-6439', '$2b$04$Q.espa6yks5QViUXIcukLO', '$2b$04$Q.espa6yks5QViUXIcukLOad6vLdf9N5t1IhmFqKow32esGOHFzNi'),
	('Jessia Zhou', 'B+', 'Jessia Zhou@gmail.com', '582 S Newsum', '1955-07-19', '669-539-8191', '$2b$04$B6M9pVN7RABbTwnNsu8t6e', '$2b$04$B6M9pVN7RABbTwnNsu8t6eToGTplvUiv1GTEnlZddf/o1cYSjJGim'),
	('Campbell Perkins', 'O-', 'Campbell Perkins@gmail.com', '321 E Brooksedge', '1959-06-23', '170-288-7498', '$2b$04$tnOi45zPIGZDU9NUoYCLNe', '$2b$04$tnOi45zPIGZDU9NUoYCLNeLWh75wBSQ8fVULIAP4C0O504ZLDDPmO'),
	('Riley Stephens', 'O-', 'Riley Stephens@gmail.com', '996 N Ashbrook', '1992-05-01', '309-788-3136', '$2b$04$lx.wOVBqOlZR2wDtQvD7lO', '$2b$04$lx.wOVBqOlZR2wDtQvD7lOs2Rqs/SpPeE9nGg4/HEIr4Sniw.DIRK'),
	('Elam Herman', 'AB+', 'Elam Herman@gmail.com', '118 W Green Clover', '1933-08-01', '680-940-1199', '$2b$04$NvdKyp6YlTyAU6.Fdxtu9.', '$2b$04$NvdKyp6YlTyAU6.Fdxtu9.nB6FfVBI7j37M2TI51/TcDJwNdWy2r2'),
	('Nonie Brandon', 'AB-', 'Nonie Brandon@gmail.com', '860 S Ealing', '1956-10-07', '120-890-6824', '$2b$04$fTh/5ZnEHjjW/ksLthXjlu', '$2b$04$fTh/5ZnEHjjW/ksLthXjluRZztGeQ.SlQlakj8CQr.QG/WTyJCeTm'),
	('Cheria Stanley', 'AB-', 'Cheria Stanley@gmail.com', '2 S Jermyn', '1999-10-09', '645-619-7608', '$2b$04$/yW4OjbDOQU1snNZQi4K5u', '$2b$04$/yW4OjbDOQU1snNZQi4K5uqkneTiar873lUnZyvmIfvN3GOI.QgfW'),
	('Huan Griffin', 'AB-', 'Huan Griffin@gmail.com', '918 N Duncaster', '1946-05-12', '492-500-9957', '$2b$04$izXlGkkkv9PJpLNNLJFyu.', '$2b$04$izXlGkkkv9PJpLNNLJFyu.2dNk2gpDVTZX0a5NeUK2891L4AFAKFu'),
	('Piers Tuttle', 'A-', 'Piers Tuttle@gmail.com', '471 E Camara', '1974-06-14', '208-688-1065', '$2b$04$D46v60fTmxXxJptPInTkye', '$2b$04$D46v60fTmxXxJptPInTkyelTqM.lBA99hQOSHDx4YGRmpQ7pSB59i'),
	('Titus Middleton', 'A+', 'Titus Middleton@gmail.com', '784 E Mchenry', '1978-04-28', '844-351-7395', '$2b$04$0jtMPUHeD6Ekc.oEvYbSYO', '$2b$04$0jtMPUHeD6Ekc.oEvYbSYOcVv97dapoS/IlYeTYX7/fiU/T2EW3TO'),
	('Nickolaus Strauss', 'A-', 'Nickolaus Strauss@gmail.com', '848 N Keystone', '1942-09-06', '366-848-3541', '$2b$04$km3sFfnqXvByZ27dNURag.', '$2b$04$km3sFfnqXvByZ27dNURag.PRNbGgfuZahl1XCvrBD6BLWCW.LnXUG'),
	('Granville Braswell', 'AB+', 'Granville Braswell@gmail.com', '975 E Ole Pike', '1950-05-14', '483-794-2746', '$2b$04$HbN.Exbh1S04EtxP3Q1J4e', '$2b$04$HbN.Exbh1S04EtxP3Q1J4edTxgT72cR.N1npwn9rczxvAhc9gCSHy'),
	('Britney Cooke', 'B+', 'Britney Cooke@gmail.com', '406 N Abbott', '1932-03-28', '129-870-7871', '$2b$04$SWKfsoBmT9PRwA4gqbNolO', '$2b$04$SWKfsoBmT9PRwA4gqbNolO6uYWs.jxyQhI/4vhDv/SLeJpY5YDkXC'),
	('Jaylon Brandon', 'AB-', 'Jaylon Brandon@gmail.com', '144 N Pete Mitchell', '1997-03-19', '263-475-6296', '$2b$04$2.DhHgPQ8eKaB417j6fxnO', '$2b$04$2.DhHgPQ8eKaB417j6fxnOygwgxg/nX4C41NAUuHzTHXEsEBwbXai'),
	('Diana Dickens', 'O-', 'Diana Dickens@gmail.com', '452 W Duckhorn', '1933-01-14', '245-306-4201', '$2b$04$geULuZF.QqI6VsGgAY2E3O', '$2b$04$geULuZF.QqI6VsGgAY2E3OsMf5EdsmFD0Uac2BaXgsECOYzZKRaTW'),
	('Stevie Blum', 'B-', 'Stevie Blum@gmail.com', '432 N Effingham', '1949-11-04', '410-132-8957', '$2b$04$ouKwWG8I8u0EhjbMVcLSrO', '$2b$04$ouKwWG8I8u0EhjbMVcLSrO8Ra7JHjtb.lzN0KZaWU/p.Q.5nuVVqi'),
	('Janneth Browning', 'AB+', 'Janneth Browning@gmail.com', '675 E Hanson', '1993-12-01', '843-374-7459', '$2b$04$.ueEBdHrHZ1nV164uxpCM.', '$2b$04$.ueEBdHrHZ1nV164uxpCM.fG1mp.YKrVcFNGJmXlfi4Kw.PHFJUMe'),
	('Ambera Lowry', 'O+', 'Ambera Lowry@gmail.com', '422 N Wickshire', '1933-07-02', '682-639-3493', '$2b$04$r6FHHdNJcQDnb/6GwPTuz.', '$2b$04$r6FHHdNJcQDnb/6GwPTuz.fG/1wZRTdGhRv5kyiCoX.rkzJzgmrRC'),
	('Davetta Bryant', 'AB-', 'Davetta Bryant@gmail.com', '224 N Parker', '1963-08-03', '718-212-2589', '$2b$04$HbviWCRcXpfmDZiEFs.NAO', '$2b$04$HbviWCRcXpfmDZiEFs.NAO5KyVNObrixRhnyK9mSlQw79E3GfwLbK'),
	('Kien Blackwell', 'A-', 'Kien Blackwell@gmail.com', '254 W Claiborne Farm', '1959-11-21', '710-533-7618', '$2b$04$jjD72cG9KJxH5x8x..je2u', '$2b$04$jjD72cG9KJxH5x8x..je2uc/u48SvdKSFyKaJsaiuF11WmH59NUTm'),
	('Jowan Wolf', 'B+', 'Jowan Wolf@gmail.com', '257 W Old Mill', '1956-11-09', '554-464-1781', '$2b$04$Qxs9oW2af3nBfBT1OX9g4O', '$2b$04$Qxs9oW2af3nBfBT1OX9g4O6IOtPeTmekiac0OmIWt5XnlNzoLqwV.'),
	('Yvonna Thomson', 'AB+', 'Yvonna Thomson@gmail.com', '298 S Rutherford', '1996-09-27', '267-881-1034', '$2b$04$GajlK.uZyMNM5X5t8Bf2fe', '$2b$04$GajlK.uZyMNM5X5t8Bf2femGcprG.4dUS3Be8wnHP7MwyfYU53vs.'),
	('Tannia Harrington', 'A+', 'Tannia Harrington@gmail.com', '510 W Sunny Creek', '1962-09-23', '566-175-7072', '$2b$04$BaVDUPaegSfFme3ncSa7le', '$2b$04$BaVDUPaegSfFme3ncSa7le43v7pB9rtQwmFB2Plv4SxreTIJeExjS'),
	('Karma Johnston', 'B-', 'Karma Johnston@gmail.com', '289 S Forest Hill Irene', '1992-05-23', '377-128-1007', '$2b$04$XrsV9P2TtI5OKWOHWU49he', '$2b$04$XrsV9P2TtI5OKWOHWU49heDkfGoj6QstXl9g5W0iheGuO5seFujUK'),
	('Brodey Floyd', 'B-', 'Brodey Floyd@gmail.com', '88 E Long Lake', '1964-06-01', '673-419-5038', '$2b$04$mbhk1AmVqNXFMcvzqNqhlu', '$2b$04$mbhk1AmVqNXFMcvzqNqhluRerhBCrBamHUAh65JxQw1a2oIozGG7u'),
	('Lashannon Sanders', 'B-', 'Lashannon Sanders@gmail.com', '648 N Fountainside', '1952-08-07', '482-958-9889', '$2b$04$nu4BtpDQNEaX9VCFgP2B8e', '$2b$04$nu4BtpDQNEaX9VCFgP2B8eO4DZG37FU8NvaY.iZw859777DTYhKEa'),
	('Janece Finley', 'O+', 'Janece Finley@gmail.com', '811 S Mustang', '1991-03-25', '566-833-9047', '$2b$04$RYpDFFkTkVRfz7k5tKbUn.', '$2b$04$RYpDFFkTkVRfz7k5tKbUn.D4o7lFp.3Ub5kJ.uhajeJMfUBe2C.Si'),
	('Vicenta Bailey', 'B-', 'Vicenta Bailey@gmail.com', '109 N Winding Creek', '1990-11-09', '518-117-1769', '$2b$04$.Z9iw28IsBCmeBmZ4l0o2.', '$2b$04$.Z9iw28IsBCmeBmZ4l0o2.ZWBeRL6zYBzplj4GspuLlZP5WKPGLFW'),
	('Dixon Lassiter', 'AB+', 'Dixon Lassiter@gmail.com', '418 E Belgrave', '1970-11-08', '383-836-6942', '$2b$04$zgsLqgMnqgvXBihYrRzBKO', '$2b$04$zgsLqgMnqgvXBihYrRzBKO2sn7FLzx112SGNSHHDEjR0jCS5tL7Ku'),
	('Marquice Corbett', 'AB-', 'Marquice Corbett@gmail.com', '544 W Northridge', '1978-06-11', '212-133-1306', '$2b$04$G5UzLdxEVZ13a7ri6fgRuu', '$2b$04$G5UzLdxEVZ13a7ri6fgRuuiG6/hW/Jm4xOvyqLhndavbB2gIaP6Le'),
	('Keidra Crowell', 'B-', 'Keidra Crowell@gmail.com', '279 W Redhaw', '1952-07-09', '250-832-5768', '$2b$04$H2fcSATydz3ExCQMB2ijPO', '$2b$04$H2fcSATydz3ExCQMB2ijPOZkEPhd/4r3fZL6nCaQVhUueHcu2KWMK'),
	('Deontray Ashley', 'O-', 'Deontray Ashley@gmail.com', '627 W Pine', '1932-11-03', '557-205-2434', '$2b$04$liaZNnglA85IUghmaEtq9e', '$2b$04$liaZNnglA85IUghmaEtq9ePJtJtT1RKiYt7c0xUkTlYhttI9upmPW'),
	('Tymel Barnett', 'B+', 'Tymel Barnett@gmail.com', '14 W Meadowlark', '1957-08-25', '597-942-4010', '$2b$04$qLFqqwa8R7BV38WR3YNLcu', '$2b$04$qLFqqwa8R7BV38WR3YNLcuIzbas/7736rCZQigYZLU7ZJ7qhwOCmu'),
	('Lynetta Nguyen', 'A-', 'Lynetta Nguyen@gmail.com', '621 S Cross Ridge', '1998-12-26', '470-731-8078', '$2b$04$4vfnNTwSnFYziezi01cR2e', '$2b$04$4vfnNTwSnFYziezi01cR2e4d47fV92t5bF0UgTslm9FfgQvovT99e'),
	('Sian Weiner', 'O-', 'Sian Weiner@gmail.com', '935 N Misty Creek', '1988-02-24', '551-855-7551', '$2b$04$ocrxfoD36RSBCPOaQEDS8e', '$2b$04$ocrxfoD36RSBCPOaQEDS8eXUWWYsi5nDDlMD9wEXjbqdeurPwR.DW'),
	('Denton Simpson', 'AB+', 'Denton Simpson@gmail.com', '5 S Redfield', '1971-07-16', '882-456-8198', '$2b$04$KJo9SkksITAEmYqtLmEKQ.', '$2b$04$KJo9SkksITAEmYqtLmEKQ.gUY/0Sv0EwxQo1j4AlXOZAgYT0/n4r2'),
	('Cortina OConnell', 'A+', 'Cortina OConnell@gmail.com', '632 W Paddock', '1989-08-26', '861-625-6164', '$2b$04$Ky9HomlgoUSR9mfYNFu58u', '$2b$04$Ky9HomlgoUSR9mfYNFu58uTsbvQwHkvVux.fH/Eb2DsnHH.ff6Jz.'),
	('Danyale Bell', 'A-', 'Danyale Bell@gmail.com', '842 N Everwood', '1973-09-19', '363-275-6232', '$2b$04$kzBYAMmjNY0a2h70vmGxG.', '$2b$04$kzBYAMmjNY0a2h70vmGxG.VV8HQpr3jenE1j/LiaxOn3ZczpH79Lm'),
	('Lashonda Gardner', 'B-', 'Lashonda Gardner@gmail.com', '310 W Waverly', '1951-03-10', '221-575-3761', '$2b$04$vCpSvkuRk21OhJlESkRs..', '$2b$04$vCpSvkuRk21OhJlESkRs..l6yv2XTSKmDcpNJhk4O6NmsWbTdDbXe'),
	('Mykal Ashley', 'O-', 'Mykal Ashley@gmail.com', '946 E Corporate Edge', '1986-06-12', '633-926-3195', '$2b$04$rpLQfENS711oyIiG9ZuXLe', '$2b$04$rpLQfENS711oyIiG9ZuXLeaMfMT5qhAiebU3Lv231PhjFRjc94mOy'),
	('Nakeesha McKenna', 'AB+', 'Nakeesha McKenna@gmail.com', '871 W Moore', '1954-05-02', '932-163-6780', '$2b$04$rZwRjGdlpBMQYKzk.QJE0.', '$2b$04$rZwRjGdlpBMQYKzk.QJE0.ustHhLHIbX4q1wkcMQGjD7SIybyoGs6');

INSERT INTO blood_bank (ManagerId, StreetAddress) VALUES
	(13, '723 S Apahon'), 	
	(11, '633 W Winchester'),
	(20, '603 S Victoria'),	
	(23, '172 W Pyron Oaks'),
	(15, '215 W Hillside'),	
	(28, '728 S Shadeley'),	
	(32, '469 N Deep Valley'),
	(7, '318 N Park'),			
	(14, '82 W Robin'),
	(1, '330 S Greensprings');

INSERT INTO blood_bank_employee (EmployerId, FullName, DateOfBirth, Ssn, PasswordSalt, PasswordHash, HomeAddress, PhoneNumber) VALUES
	(10, 'Abena Mueller', '1980-08-24', 6403921, '$2b$04$1fITnC4r.htJEFui2Fh61O', '$2b$04$1fITnC4r.htJEFui2Fh61OvSshADLbtGQTGy5VJXfe9X2OZJ9LgmW', '401 E Cedarville', '863-966-2444'),
	(1, 'Vaneza Frank', '1971-08-21', 5469766, '$2b$04$rECXATN.wy.NaiVaxr0QN.', '$2b$04$rECXATN.wy.NaiVaxr0QN.4WLiKqssY8rjfxP9k572HIpBtJa25Yy', '791 W Hampton Grove', '828-741-9045'),
	(2, 'Jacki Corbett', '1993-09-27', 4993822, '$2b$04$CzynL22QwSP4NPx6M3IO/e', '$2b$04$CzynL22QwSP4NPx6M3IO/eWkVLY07DF586gOxLNksu.Mdhkh/IU.K', '949 S Minar', '703-348-5546'),
	(8, 'Janesha Knight', '1985-10-28', 2714363, '$2b$04$2Tjb7xVKeN0WIk3JWXtkUO', '$2b$04$2Tjb7xVKeN0WIk3JWXtkUOzYm/3DWjgAjCt0KYrhy4drNyjeOi8GC', '364 W Merenerm', '830-633-6981'),
	(10, 'Lawson Gonzalez', '1971-10-09', 6074404, '$2b$04$CrFppyokjrtiymkm1TvdHe', '$2b$04$CrFppyokjrtiymkm1TvdHeOeCYwGCjcnEsE0bPuX/g/A1xjbQAhCG', '907 N Monte Vallo', '475-539-7833'),
	(5, 'Phylis Payne', '1987-03-09', 9917216, '$2b$04$zcG9vAGPsC9fEeu7eIrENO', '$2b$04$zcG9vAGPsC9fEeu7eIrENOfAJynzeMdYr17QxCeY2oIYk2QvSZESS', '50 S Grasshopper', '578-443-4320'),
	(8, 'Derrelle Mayo', '1951-03-11', 8586584, '$2b$04$RVk3LIC5EJFDTkIwP48IRu', '$2b$04$RVk3LIC5EJFDTkIwP48IRulOjgzl68xA7kta9Zc5ABO5e0bFcD3Zy', '804 W Ottawa', '143-950-6304'),
	(10, 'Anel Hardison', '2000-12-19', 7027349, '$2b$04$StxtZIV1m.SrwFv5XeEZgO', '$2b$04$StxtZIV1m.SrwFv5XeEZgO8FHhUdWR0BHFFb3Df7oUcHMqa8u1BY2', '673 E Sunset', '698-521-6892'),
	(8, 'Felina Wooten', '1943-09-13', 2642456, '$2b$04$eIeANHC9g/72An2ovvyqqe', '$2b$04$eIeANHC9g/72An2ovvyqqeHpk875PovoCkt9FHML6PJGsRJuJutgm', '380 N May Woods', '419-320-6510'),
	(10, 'Reilly Goldberg', '1972-06-27', 1821633, '$2b$04$8l0BteaOVD9QgnKrD26i/O', '$2b$04$8l0BteaOVD9QgnKrD26i/OIcEwz8Fn.M2PRmW7zDP/c88q51ETu/O', '111 N Redhaw', '623-183-5629'),
	(2, 'Billiejo Matthews', '1987-12-10', 9514976, '$2b$04$CoZzv9QIULZdW5pXVNgKDO', '$2b$04$CoZzv9QIULZdW5pXVNgKDO5BnEH8/wEf3Pcj4bCTM15hsDWzAzJnS', '39 E Old Post', '323-465-8363'),
	(10, 'Zerrick Craig', '1939-04-15', 5439104, '$2b$04$BR.XNmxlnXrWiqp68Gq.p.', '$2b$04$BR.XNmxlnXrWiqp68Gq.p.RisAESFVxqU2Dq7jcl8jZ.aYfAIwXZq', '576 W Rowlock', '508-607-8898'),
	(1, 'Dexton Mack', '1936-01-17', 6987848, '$2b$04$ECoyi6obJdPueP0COwnXWu', '$2b$04$ECoyi6obJdPueP0COwnXWu5a/Ot7bodNuAxMdrBHYMcSsY18FxQDC', '359 E Wolf Park', '407-524-4293'),
	(9, 'Demetria Bowden', '1972-11-23', 9275046, '$2b$04$w83i6bEgEuzPOETky.Z/Ee', '$2b$04$w83i6bEgEuzPOETky.Z/EeH9XIew.htncrG7zzkJr1QDGnLBRO6yC', '277 S Dairy Ashford', '420-499-6291'),
	(5, 'Chazz Frye', '1948-10-02', 8475885, '$2b$04$CWmImuPObnqsV21MCELsJu', '$2b$04$CWmImuPObnqsV21MCELsJuxGZI6IR3lcWE91/qPEYqoyN.T2/cRMe', '405 E Ainsworth', '970-817-9689'),
	(8, 'Garo Moser', '1994-10-19', 4057688, '$2b$04$wUmgG4/8BOXSDKDuaiMyAO', '$2b$04$wUmgG4/8BOXSDKDuaiMyAOj2avdP.o/KN5qJtcoyD313cbLnoSHN6', '736 E Newsum', '726-989-9865'),
	(3, 'Shawnie Reilly', '1943-08-22', 8717919, '$2b$04$6naJawxuaOzJMmqSSLHzT.', '$2b$04$6naJawxuaOzJMmqSSLHzT.tphX8jeTsdFznGLyT1MNEwe9VAI/JaW', '480 N Arthur', '652-488-2268'),
	(2, 'Mirel Lim', '1992-11-05', 3634692, '$2b$04$5bWjUjVS9ASlJZOTRcnIqe', '$2b$04$5bWjUjVS9ASlJZOTRcnIqeRpvSJuE3wetqJeG9MWGXoIsj2WRXOR2', '858 W Woodbend', '476-632-7843'),
	(5, 'Ysenia Singleton', '1964-12-04', 4871023, '$2b$04$8DbuALgGNctL6yjssetFTu', '$2b$04$8DbuALgGNctL6yjssetFTuKVQtSWwbl97vrlaIN0lHui/Cv7q/xv2', '712 E Maple', '673-772-2241'),
	(3, 'Corrine Powell', '1996-07-05', 1218853, '$2b$04$pKnwQ1/qJZzc3DcgpnA01O', '$2b$04$pKnwQ1/qJZzc3DcgpnA01O5vb98kD0Os6wksXHdG2R2d2NngVsmiW', '344 W Kimbrough', '766-256-7268'),
	(2, 'Mai Proctor', '1932-04-05', 7339170, '$2b$04$DD4/SLHQ9fFcgxaz1uxAY.', '$2b$04$DD4/SLHQ9fFcgxaz1uxAY.NTt1UYDIxdTe3XD63Kvni5Z7f4GB17i', '640 E Pete Mitchell', '331-495-9491'),
	(8, 'Nakeita Rose', '1948-04-17', 3993844, '$2b$04$Bhzo.SZ04dYHDOFji33Ja.', '$2b$04$Bhzo.SZ04dYHDOFji33Ja.I.pb9uD1ttEs3EiAhOcVjPc3WIwe1d2', '990 N Tallwood', '714-474-5882'),
	(4, 'Chelise Donovan', '1960-09-25', 8403499, '$2b$04$jEN8MRTsv6muWUaKqZeQAO', '$2b$04$jEN8MRTsv6muWUaKqZeQAO80rsbdt/Aep6JyxGwVav0D7XpY14U9K', '50 N Creathwood', '663-182-7458'),
	(3, 'Terrion Moss', '1946-06-28', 6564804, '$2b$04$kT7yDvOcS.6GvThjUz9Mo.', '$2b$04$kT7yDvOcS.6GvThjUz9Mo.UKnjRACeZ98YlzQ6wQtUn//zCSvTNgi', '360 E Circleshade', '404-869-5039'),
	(7, 'Sadae Solomon', '1993-07-26', 4266209, '$2b$04$yGs47pxkxNoR7eW4GOg0oe', '$2b$04$yGs47pxkxNoR7eW4GOg0oeBm1CqES4bm.kdi1NvUPkQgh6sl3OYEC', '442 W Watkins', '505-781-8065'),
	(4, 'Eliu Mills', '1986-03-10', 5701562, '$2b$04$iGpxhQu/yCLq5puZqPyAlO', '$2b$04$iGpxhQu/yCLq5puZqPyAlOV7q7tZkKeqXcv07edHylyIL3tEZu39y', '158 E Gershwin', '448-583-2284'),
	(10, 'Pieter Corbett', '1967-01-03', 4621992, '$2b$04$fIFdCibK16c1aQJAVi8pCO', '$2b$04$fIFdCibK16c1aQJAVi8pCOmsLt/nJND2QQ3i9SvLUgl5nElRMIgUO', '505 E Diamond Leaf', '257-996-6962'),
	(6, 'Ainslee Mathews', '1961-03-23', 2669599, '$2b$04$uBqdbmyVVpeunb4aLLQDye', '$2b$04$uBqdbmyVVpeunb4aLLQDyeySWrZpGeb4qY0az92OUXcN6/124cVrC', '673 W Barkers Point', '324-657-9902'),
	(0, 'Delonta Zhang', '1941-01-15', 3220268, '$2b$04$AtbxLwP9lXUkvIvO9mMENu', '$2b$04$AtbxLwP9lXUkvIvO9mMENuFR0HdeNhzLVhlJUM5v5cEvlDNUAlyVe', '196 W Ashmont', '120-326-4526'),
	(6, 'Roche Cain', '1990-01-17', 5375087, '$2b$04$Td.TTOXVhIc371X34nYDmO', '$2b$04$Td.TTOXVhIc371X34nYDmOUDWjGa.GxzUzuB1b8QIWBFS2Db4/eca', '906 E Sweetwood', '511-892-1050'),
	(10, 'Chett Allison', '1967-06-03', 2074519, '$2b$04$m1VL8pSkQMsbTWSuAFDwlO', '$2b$04$m1VL8pSkQMsbTWSuAFDwlOC7YwOj6bQ3/jDn3liI2AVwFmwdTe1QW', '831 S Briar Knoll', '467-817-3564'),
	(7, 'Lonnie McLeod', '1971-09-03', 1264876, '$2b$04$thVnnA1tbHgSlGbtxnp01O', '$2b$04$thVnnA1tbHgSlGbtxnp01OxDSX6l/Cbqdr0SF7TBT5vYC0qPClTxO', '3 W Moss Tree', '354-782-5675'),
	(6, 'Mieko Flynn', '1935-02-21', 1723600, '$2b$04$iRFTeLG2JrmSX61bEVvIB.', '$2b$04$iRFTeLG2JrmSX61bEVvIB.Jo.NUbiGYhorvF.ykRUVOgBSfTYhQBW', '316 S Rainwood', '727-735-9383'),
	(4, 'Christoher Bishop', '1998-12-19', 9328007, '$2b$04$j1.1ww4DYJeTKfDIbGrqZe', '$2b$04$j1.1ww4DYJeTKfDIbGrqZe7bp4qnSFkMvoXJXoEms7.oP.JwAtHDe', '664 W Danforth', '904-482-5889'),
	(4, 'Leander Tate', '1935-10-17', 5698757, '$2b$04$AR2q/pwUJarHipoAxojLnO', '$2b$04$AR2q/pwUJarHipoAxojLnOYfExz7mIYLqSG8iMHPBzLjJFyr6N/le', '862 N Greenpark', '935-539-2163'),
	(8, 'Zully OConnor', '1979-02-11', 7013668, '$2b$04$xkN8iJvatHQ9TGXiD9zS7u', '$2b$04$xkN8iJvatHQ9TGXiD9zS7uckfm/EXo0NX8pKV71TYDXDcrdgHz1yC', '14 W Martha', '465-836-2785'),
	(9, 'Curtrina Starr', '1986-10-10', 5347185, '$2b$04$hUZpvrxMwQ10h0jjhlK5c.', '$2b$04$hUZpvrxMwQ10h0jjhlK5c.wTRG4CEKH6MnJgP7fwt58S2itbxZ6sG', '936 N Landfair', '846-571-5537'),
	(10, 'Donvan Cherry', '1968-05-20', 9441019, '$2b$04$KljzM4PVFah3E7vyGeKi9u', '$2b$04$KljzM4PVFah3E7vyGeKi9uRkXU/L3E7yPHItm.6qNdSp0U6uPrF2a', '302 W Riverwood', '317-636-3243'),
	(8, 'Ren ONeill', '1940-09-14', 2003947, '$2b$04$vz19/SUR.bXV1SqVa1nTNu', '$2b$04$vz19/SUR.bXV1SqVa1nTNuM0h6CDUF2QAJ6rcFXRnSoXatwz8hqR6', '639 S Green Pastures', '452-858-9267'),
	(4, 'Cherisse Watts', '1993-03-27', 6327261, '$2b$04$n3H11VDIV/UQ24GdE23BnO', '$2b$04$n3H11VDIV/UQ24GdE23BnOoGPrW8EGFC1oBNpSkUKjrpuIBoOT7rO', '400 W Newberry', '436-512-2111'),
	(3, 'Trena Palmer', '1989-01-23', 5955521, '$2b$04$f/S07UvKdvQTbv8T1sRC8.', '$2b$04$f/S07UvKdvQTbv8T1sRC8.F3kWbdgiswDYjaD6oR.0IyjYqLLuZKO', '509 E Penrose', '604-976-3045'),
	(7, 'Belinda Clayton', '1957-01-11', 4353463, '$2b$04$0ONmo/7818ZPg4Z2ed5fme', '$2b$04$0ONmo/7818ZPg4Z2ed5fmen6F6GkWYOdK6IUxoyxq4O0N46M6/1Si', '940 S Arden Walk', '297-112-6727'),
	(3, 'Shafiq Grady', '1987-01-18', 7687231, '$2b$04$g8.ejcLiM6KJ/D4NaqTRGu', '$2b$04$g8.ejcLiM6KJ/D4NaqTRGucf1C0g86YLkxl/zRyVmPRHtgCPyNoGK', '261 N Oak Manor', '171-428-1131'),
	(0, 'Desmond Kenney', '1969-03-27', 2095187, '$2b$04$uMXfp/7i/mt/Uok7AyWj8O', '$2b$04$uMXfp/7i/mt/Uok7AyWj8O0wHnNpcnPJ8JcTOaF6Zyox/4IOZGTcW', '145 W Dian', '540-541-9245'),
	(8, 'Chantille Clements', '1958-03-25', 2563617, '$2b$04$A7XNxgXBq2H5Gi.LMs225O', '$2b$04$A7XNxgXBq2H5Gi.LMs225OU8agxvqg7/my8mWHdJj4tPd/tNrI6tS', '924 W Dragonfly', '600-348-7588'),
	(6, 'Aquil Huang', '1999-08-10', 9795187, '$2b$04$uTpED/C6/zJAjEPsyT3Mlu', '$2b$04$uTpED/C6/zJAjEPsyT3Mlu5dXKGwTjwqLRCloKzyM6drxtzubuK/u', '915 W Forestwood', '442-902-2484'),
	(2, 'Danicia Yates', '1997-10-22', 7920078, '$2b$04$NaYieYMBZQ2p81vwaQINcu', '$2b$04$NaYieYMBZQ2p81vwaQINcu/xUw6dS46MUDmP8nhL1ZUMi/zJ5ABc.', '569 S Rummel Creek', '387-282-4178'),
	(2, 'Zebariah Robertson', '1967-06-08', 4869028, '$2b$04$hVZYsQ6mR5XvXQy7d4FKBe', '$2b$04$hVZYsQ6mR5XvXQy7d4FKBeaRZWUSqEHPYhmJFVl0dadqnGdyquQ2i', '804 N Old Deer', '405-171-7972'),
	(0, 'Catalino Pickett', '1988-11-18', 5087587, '$2b$04$0IdIw9Hku8OVNnAGFrusmO', '$2b$04$0IdIw9Hku8OVNnAGFrusmOceFn.HCDI0c6A8NlnvyT3tSwN.IvZGy', '749 S Heatherbrook', '938-594-3465'),
	(6, 'Prescilla Rouse', '1934-06-02', 4968916, '$2b$04$QmH0N8nQCshRTvB1bsI6ye', '$2b$04$QmH0N8nQCshRTvB1bsI6ye9Esah4lmSYjA4n8QnxPIqKgJgkJlI92', '448 N Carolcrest', '882-657-7101'),
	(4, 'Antroine Epstein', '1944-12-21', 4885473, '$2b$04$AYw7UPFn4f8TenynSJtoBO', '$2b$04$AYw7UPFn4f8TenynSJtoBORLO2HJG6REdesefWqp9D5YHMak9CZ7u', '749 S Perkins', '225-791-7797'),
	(7, 'Blayne Peterson', '1998-11-21', 2660501, '$2b$04$CqlmvA7b/aqTsRIr6fhIHu', '$2b$04$CqlmvA7b/aqTsRIr6fhIHuPz5U.564P8pUjPEJGneal9JuJ5o2cSq', '505 S Eben', '243-276-3488'),
	(8, 'Carissia Whitfield', '1977-09-12', 4394431, '$2b$04$vHqYB0SLTiquyCj48JPZpu', '$2b$04$vHqYB0SLTiquyCj48JPZpuvzIHBIpXr3F7AmWc/.udOmzdSnggAXe', '747 N Brenley', '162-407-6877'),
	(6, 'Nikkole Pennington', '1962-06-09', 9244254, '$2b$04$7bBzudRCnSzWnuimfszQz.', '$2b$04$7bBzudRCnSzWnuimfszQz.T3t14HRgABKkpoj8VNUn56DIK/4rzye', '591 E Silverbark', '361-487-8348'),
	(8, 'Nekia Hirsch', '1991-10-27', 4174257, '$2b$04$bm3Dj13aCBXSyjMD2nNcAO', '$2b$04$bm3Dj13aCBXSyjMD2nNcAOiTRPmlIcxtk7F/CbUtHpE43v0T1r5.G', '600 N Twisted Oak', '897-749-7031'),
	(2, 'Nickalaus Choi', '1976-12-10', 4779376, '$2b$04$KRHPOMbCkgkYH.ftb1OlOu', '$2b$04$KRHPOMbCkgkYH.ftb1OlOuYPMdjzkOLsHnLOUqOyAjdFdFshWZAye', '556 S Brewers', '288-206-9542'),
	(5, 'Travers Gould', '1940-07-10', 3377091, '$2b$04$hqkT0RdPwyYdxTlkcXTqF.', '$2b$04$hqkT0RdPwyYdxTlkcXTqF.2rKt9CqaZuQ/JaPL3/IwSGR8bvPXwEu', '706 W Rummel Creek', '497-443-3794'),
	(10, 'Gergory Bush', '1954-06-13', 2138756, '$2b$04$rixppGkXi7Xt3rjVwbY5d.', '$2b$04$rixppGkXi7Xt3rjVwbY5d.bE2Df2fbdmRsPmXjGZ6DvjotNpb8I2.', '846 W Hickory Post', '226-179-9869'),
	(4, 'Nedra McDonald', '1963-03-13', 4727801, '$2b$04$h56lUvbvsCTSuuCDymW3eO', '$2b$04$h56lUvbvsCTSuuCDymW3eOUxF.aFkptr4Lak7lgCIwbgr5ivtgepa', '362 N Mustang', '332-855-8867'),
	(9, 'Tarren Koch', '1967-04-22', 1810416, '$2b$04$fk9/ivFBvyF8u7una1FW3O', '$2b$04$fk9/ivFBvyF8u7una1FW3Oocke5ktoVx2/IWY1jRToF4M2ZFrzE4G', '369 S Everett', '311-804-9447'),
	(0, 'Diante Blum', '1966-08-28', 3642005, '$2b$04$5S2bJSQX4Cy2ENtDrJLdN.', '$2b$04$5S2bJSQX4Cy2ENtDrJLdN.Nn7cdhxWpjutQhGZJR1qKWijpiy47f.', '211 W Old Bridge', '668-255-2007'),
	(9, 'Sylvester Block', '1961-09-12', 5040354, '$2b$04$sDiyeBAuAReb.wttvwksge', '$2b$04$sDiyeBAuAReb.wttvwksge3Ytr7938csGAVWu78SWk6oL3aUdUpNS', '396 N Bradford', '754-919-5000'),
	(6, 'Khoa Hsu', '1989-05-04', 6665547, '$2b$04$Q9OXgJEkDQIev6VV1Fxd5u', '$2b$04$Q9OXgJEkDQIev6VV1Fxd5umhy.lzO4URkAlcrXzenTch/in2Mvnou', '807 N Woodridge', '798-382-2580'),
	(8, 'Jillana Shaffer', '1930-09-02', 1256723, '$2b$04$B57Q3GVq29HTKFLRGiyQtu', '$2b$04$B57Q3GVq29HTKFLRGiyQtuWWEtyFFyutIml21DVsMIzP8NsQbfqym', '698 N Patchester', '658-336-1282'),
	(6, 'Sammie Stuart', '1974-10-23', 8030584, '$2b$04$Iy39xFmsi2suEpjcL7.RX.', '$2b$04$Iy39xFmsi2suEpjcL7.RX.1MbkPxaQpbLi.sKZubWEICL/NhBMub2', '854 W Jeffrey', '436-682-1354'),
	(8, 'Karinda Carpenter', '1971-09-22', 7732009, '$2b$04$Q5DWZqenuhuG.Y5VB0cVWu', '$2b$04$Q5DWZqenuhuG.Y5VB0cVWuMyBeilSR31HzfnTe4zl2VmyYAt0Tqw6', '297 W Pittsfield', '994-229-3564'),
	(8, 'Lataisha Britt', '1944-12-16', 6689109, '$2b$04$vN1AQMoce/3MF7PfuaFHwe', '$2b$04$vN1AQMoce/3MF7PfuaFHwe/.KfyaWs0GTxEikCYuODdb7cnha111a', '216 W Poplar Woods', '374-318-9019'),
	(3, 'Michaella Peck', '1955-01-15', 9591305, '$2b$04$wZHGjh4M1I11v5EdEoA7/.', '$2b$04$wZHGjh4M1I11v5EdEoA7/.SRuWXmWVbD0dy1D55CpkAlNtbgYyd66', '772 S Oldridge', '503-883-6218'),
	(0, 'Kamira Hendricks', '1949-04-18', 3185006, '$2b$04$nKH3Hu7WeO8bMh0R1bXcau', '$2b$04$nKH3Hu7WeO8bMh0R1bXcaumZPl4qyAqcg6D0p6s5aQA8fSu0BKiTa', '635 E Carters Grove', '222-664-8153'),
	(2, 'Ivane Bean', '1981-01-19', 9296800, '$2b$04$O8Rh8f5EptNYAKtnlnF0qu', '$2b$04$O8Rh8f5EptNYAKtnlnF0quQzyNd.0nCooLXOBrRDI6xXRkxouohyK', '626 S Wargate', '720-674-5710'),
	(7, 'Jonas Hoover', '1940-06-17', 3027371, '$2b$04$BrC/q5WBW2qqqXxx1PFWPe', '$2b$04$BrC/q5WBW2qqqXxx1PFWPe2ChIizj/rkLh5HLEDgg5mUTLb1HeGta', '969 S Elmhurst', '743-668-6353'),
	(6, 'Mariadelcarmen Poole', '1994-09-12', 4184594, '$2b$04$sRz/aifE9170bDhWdS9ip.', '$2b$04$sRz/aifE9170bDhWdS9ip.9ckQMwdzFFzg13ZrTJuyBu3FTTi2QMK', '197 W Greenmeadow', '679-771-1904'),
	(5, 'Jazzmine Ray', '1946-05-03', 3988830, '$2b$04$PWTKYL.JW62zps85kYd.Tu', '$2b$04$PWTKYL.JW62zps85kYd.TuuhoHjO35pH3S0xXUlZNh8.ivYcnuJcO', '150 E Windbreak', '242-781-1997'),
	(7, 'Charisse Song', '2000-06-25', 7421199, '$2b$04$vx3V8f4u7WrzmoFBmwnySe', '$2b$04$vx3V8f4u7WrzmoFBmwnySe3RJybYT/SqmJ2GR8yWGoLjGL8b9efqK', '8 N Cornuta', '841-872-6486'),
	(6, 'Zonia Brewer', '1980-03-08', 6640043, '$2b$04$7gdNl4PhklSeyLv/xTN15.', '$2b$04$7gdNl4PhklSeyLv/xTN15.kMKYJmsCtyCncl.cNlVaNPa1cifV4LG', '569 E Deerfield', '304-231-8316'),
	(8, 'Lavada Ward', '1945-07-20', 1532473, '$2b$04$ZIWxGJYWlCq.7rD.JXiad.', '$2b$04$ZIWxGJYWlCq.7rD.JXiad.aj35r3DO3j3nyxMwWfJ2ZWFXfJKpMfO', '604 W Golden Fields', '368-439-7563'),
	(3, 'Sateria Walters', '1974-12-13', 5176220, '$2b$04$c5dde7CL6iIR8HURBxDp9u', '$2b$04$c5dde7CL6iIR8HURBxDp9ucLlQ7EJCcfEw8SH7MR6CkTovXnbN8za', '330 N Broadway', '406-710-6891'),
	(7, 'Ikaika Lewis', '1977-05-04', 7403064, '$2b$04$c5OmnynfXX2/PbyV4aSZHu', '$2b$04$c5OmnynfXX2/PbyV4aSZHuJnSw9blScYN/71djoWqtDLl/ylWSNTS', '167 W Deer Path', '153-400-1389'),
	(8, 'Naheed Harrell', '1989-07-19', 3169368, '$2b$04$ypT3jYI/OIGNq6T2ATHLMu', '$2b$04$ypT3jYI/OIGNq6T2ATHLMuWMoONfI6pLklpVuWn19ch4Mv8eCEKRS', '174 E Delano', '925-271-3171'),
	(10, 'Otisha Kumar', '1931-06-15', 9520623, '$2b$04$NwMFvE4p/e8mbWykz59Kle', '$2b$04$NwMFvE4p/e8mbWykz59KleZVxYCmmXivS29w6B35WAyMRP/rkI3zC', '190 E North', '826-738-9530'),
	(7, 'Tamie Robertson', '1992-07-15', 2036023, '$2b$04$dan.bANqfmETaH9gR5A37e', '$2b$04$dan.bANqfmETaH9gR5A37eUuplcmx1c0xrfh8OxdChkDsddWxGeCK', '945 E Grove Mill', '857-207-9941'),
	(8, 'Brannigan Wilder', '1985-02-24', 8319531, '$2b$04$RkLPBsppZGAxCMTMkFpjve', '$2b$04$RkLPBsppZGAxCMTMkFpjve5Y9P4aU5yGeYkimUOZjD8uVBg1txxoK', '399 S Blackberry Ridge', '127-153-2956'),
	(7, 'Willa Bradshaw', '1952-12-10', 7756531, '$2b$04$qge9N/vbPozkEShnDc1uI.', '$2b$04$qge9N/vbPozkEShnDc1uI.y2o.lyl/C5mZW4adILK.Zw2foMzzCR.', '219 N Golden Chance', '120-722-9483'),
	(0, 'Mitzi Stein', '1951-11-22', 2872342, '$2b$04$LrvdsYVkTJ3i7LMZuQi4su', '$2b$04$LrvdsYVkTJ3i7LMZuQi4suCnyu5jhu8z9Xm.QjC02s67yQwCSWElG', '784 E Crossflower', '280-565-7968'),
	(4, 'Ralphel Khan', '1954-08-12', 3283618, '$2b$04$lKuWWfZzqBomO9pxW.ttVO', '$2b$04$lKuWWfZzqBomO9pxW.ttVOQjtb9U18oyLNZuowM5PIr0BRG5JD4AG', '925 S Green Holly', '912-699-3686'),
	(5, 'Nasir Kearney', '1938-07-09', 5678804, '$2b$04$CirfwHgs0lGjcLpS.0Tr7.', '$2b$04$CirfwHgs0lGjcLpS.0Tr7.JZuUpIqBsaCUDqY99ntQszxvUbIhPV2', '700 W Grenville', '752-614-5678'),
	(8, 'Lakeyia OBrien', '1935-12-16', 7135803, '$2b$04$ZWyxdy.clB9/bB7xxxJY2u', '$2b$04$ZWyxdy.clB9/bB7xxxJY2uiTcm62PoBjAw5ik9F5leZtfpYikEW3C', '407 E Havenhill', '191-949-1086'),
	(10, 'Teandre Moody', '1980-09-27', 6236284, '$2b$04$xPQZROG2iv1o2uAtwgWtHO', '$2b$04$xPQZROG2iv1o2uAtwgWtHOZ5zXHyL6cQlOPFkjcQd3U0ADsQEW2e.', '260 N Sleepy Hollow', '380-917-6539'),
	(8, 'Aranda Reeves', '1972-12-23', 8649918, '$2b$04$bX8UarLWie.u2gc7EPev1.', '$2b$04$bX8UarLWie.u2gc7EPev1.Lt4XDpBfm/5Fy5QntTiP0o7MXFITRVy', '317 E Thorncroft', '508-412-4109'),
	(4, 'Ruddy Patrick', '1980-06-26', 7328752, '$2b$04$bzwUslK1NdCu78CPsB5J0.', '$2b$04$bzwUslK1NdCu78CPsB5J0..KrcBZwWuynYq9GGjTUhe1vTKSnWlG2', '988 W Hickory Glen', '116-353-5637'),
	(0, 'Suleiman Sloan', '1978-09-28', 8593157, '$2b$04$WC13Vtpc3BS9.ifXL186N.', '$2b$04$WC13Vtpc3BS9.ifXL186N.j98hhmWsB3PGQnVj9MHBYpqNVG00qTy', '13 E Maryknoll', '498-989-6402'),
	(0, 'Chalese Lynch', '1939-05-10', 2302708, '$2b$04$Xc/y5RwChbLa6n5cT6W4.u', '$2b$04$Xc/y5RwChbLa6n5cT6W4.uPxwY2cRpOauzaZUGTeEXDaSeiea60.O', '324 S Oakes', '909-786-7352'),
	(0, 'Marcella Gray', '1964-09-17', 1261299, '$2b$04$Ok9skcf09r819803nAbcle', '$2b$04$Ok9skcf09r819803nAbcle6E7mNCb5xXqnKNA4/IrTQIDAeUhZVUO', '510 W Buckingham', '349-960-2540'),
	(10, 'Tristina McNamara', '1981-11-15', 8761490, '$2b$04$DlgaUsubqv3YZnir4fi9WO', '$2b$04$DlgaUsubqv3YZnir4fi9WOF4zsRh0LkwBjXSJ42avmx92l06bG7vO', '2 E Crossflower', '718-503-9513'),
	(2, 'Stacy Kay', '1970-02-16', 3971286, '$2b$04$y0ZPCImXedciPI5xtyL/4u', '$2b$04$y0ZPCImXedciPI5xtyL/4uDqsAl0T.nDFCPLV2k/e8npI310j4P2a', '645 N Cedar Ridge', '274-222-8641'),
	(6, 'Nicklas Anderson', '1963-06-09', 2814880, '$2b$04$tj3k6yLHY70Nm9LnNrpt/u', '$2b$04$tj3k6yLHY70Nm9LnNrpt/uVdFcYJbI6rQVsIX.NDnNsDPGhVzyouK', '746 S Cotton Boll', '655-670-5221'),
	(10, 'Lindsey Haynes', '1997-05-07', 3777383, '$2b$04$gcHlfJ72gHXqML3h/hcvlu', '$2b$04$gcHlfJ72gHXqML3h/hcvluOKI.ZZO8qltjfsEPAc.bUZKaKH.VDFe', '869 E Robin', '570-560-6312'),
	(5, 'Rasean Greer', '1952-11-21', 5786157, '$2b$04$o31FDfEm.rD7IKayc9eU9.', '$2b$04$o31FDfEm.rD7IKayc9eU9.TBzdml9IQgT0yOfeL1JwQlC9XIyha1C', '382 E Sherburne', '862-581-3454'),
	(9, 'Soraida Rodriguez', '1939-08-02', 1581677, '$2b$04$1VJOdsx/BouAzfjC5roEM.', '$2b$04$1VJOdsx/BouAzfjC5roEM.IZhtbUlyP.tRaPzT2uUBE6T6X7FkwNK', '513 S Bluebird', '109-529-6487'),
	(1, 'Lyna Carroll', '1972-01-07', 8260002, '$2b$04$GVZ5pJEQB6JJcHw55t87KO', '$2b$04$GVZ5pJEQB6JJcHw55t87KO7cXxrSVUT51EfnWjw0NE5CMoV2rY1oK', '852 S Hollow Creek', '670-618-8454');

INSERT INTO hospital (HospitalName, StreetAddress) VALUES
	('Hospital A', '601 W Mystic Ridge'),
	('Hospital B', '964 N Paris'),
	('Hospital C', '686 W Sweet Oaks');

INSERT INTO hospital_employee (EmployerId, FullName) VALUES
	(0, 'Moranda Gross'),
	(0, 'Demarko Lawrence'),
	(1, 'Nickole Dixon'),
	(1, 'Benard Patrick'),
	(0, 'Tyleen Parker'),
	(3, 'Eunique Friedman'),
	(3, 'Jazzlyn Atkinson'),
	(1, 'Tauni Dickerson'),
	(3, 'Breean Aldridge'),
	(0, 'Ritu Conrad'),
	(1, 'Adaliz Diaz'),
	(2, 'Rania McMahon'),
	(1, 'Valerie Tate'),
	(0, 'Lenora OConnell'),
	(3, 'Shiana Woodruff'),
	(0, 'Derius Ward'),
	(2, 'Kyoko Bolton'),
	(0, 'Sarika Lin'),
	(0, 'Baudelia Combs'),
	(1, 'Bevin Price'),
	(0, 'Jarmaine Taylor'),
	(2, 'Desaray Raynor'),
	(1, 'Doris Allen'),
	(2, 'Kip Hewitt'),
	(1, 'Alece Whitaker'),
	(1, 'Verlin Vincent'),
	(2, 'Tavis Murray'),
	(3, 'Sabreen Levy'),
	(2, 'Chante Pearce'),
	(1, 'Kaleem Merrill'),
	(3, 'Tavoris Puckett'),
	(1, 'Megumi Simon'),
	(1, 'Stephone Adcock'),
	(2, 'Daisy Nguyen'),
	(2, 'Newman Heath'),
	(2, 'Aquanetta Adams'),
	(1, 'Martha Sherman'),
	(0, 'Marykate Lamm'),
	(1, 'Nocole Crews'),
	(0, 'Tresa Howe'),
	(0, 'Eduardo Denton'),
	(0, 'Rockwell Sutton'),
	(2, 'Tenille Eason'),
	(2, 'Huma Payne'),
	(0, 'Cherry Patton'),
	(0, 'Michael Kendall'),
	(3, 'Breeanna Holt'),
	(1, 'Brendin Harrell'),
	(2, 'Kelse Robinson'),
	(2, 'Samuell Middleton');

INSERT INTO blood_transfusion (EmployeeId, TransfusionDate, Amount, RecipientId) VALUES
	(39, '2016-09-09', 2, 51),
	(65, '2019-09-13', 1, 31),
	(99, '2018-01-12', 1, 71),
	(31, '2016-06-05', 2, 23),
	(10, '2021-03-20', 5, 18),
	(74, '2018-05-14', 5, 41),
	(8, '2020-08-09', 3, 81),
	(0, '2020-04-17', 1, 3),
	(49, '2020-07-02', 3, 5),
	(38, '2018-12-18', 2, 2),
	(9, '2021-03-05', 1, 54),
	(10, '2020-09-04', 3, 91),
	(83, '2021-03-19', 1, 15),
	(51, '2017-04-03', 3, 72),
	(1, '2017-05-20', 1, 0),
	(60, '2016-12-12', 4, 2),
	(82, '2020-01-08', 3, 88),
	(85, '2018-07-13', 1, 46),
	(26, '2021-03-21', 5, 69),
	(93, '2016-12-07', 1, 57),
	(54, '2018-08-06', 4, 98),
	(75, '2019-09-09', 5, 22),
	(49, '2019-01-12', 3, 74),
	(88, '2020-06-24', 1, 30),
	(14, '2022-10-09', 1, 6),
	(53, '2015-05-01', 2, 0),
	(100, '2017-01-16', 5, 98),
	(60, '2020-05-03', 4, 8),
	(17, '2021-01-26', 5, 96),
	(11, '2016-04-04', 3, 44),
	(96, '2017-11-27', 3, 94),
	(76, '2017-07-10', 1, 13),
	(30, '2015-01-22', 2, 92),
	(66, '2017-06-05', 1, 32),
	(30, '2017-07-22', 3, 70),
	(6, '2021-03-08', 1, 95),
	(75, '2016-05-01', 3, 34),
	(61, '2018-07-17', 1, 25),
	(95, '2016-08-01', 1, 81),
	(76, '2021-02-11', 1, 92),
	(0, '2016-07-22', 2, 96),
	(95, '2018-01-27', 2, 4),
	(90, '2019-02-21', 1, 35),
	(40, '2016-01-28', 1, 72),
	(22, '2015-12-18', 1, 9),
	(81, '2021-01-08', 3, 79),
	(59, '2015-04-20', 1, 53),
	(64, '2018-08-27', 5, 34),
	(12, '2021-10-05', 1, 77),
	(76, '2016-05-09', 2, 30),
	(18, '2017-05-24', 4, 4),
	(93, '2017-02-17', 1, 30),
	(77, '2015-10-25', 4, 22),
	(8, '2019-10-26', 1, 6),
	(81, '2017-06-14', 2, 87),
	(40, '2017-08-15', 2, 11),
	(80, '2019-08-17', 2, 23),
	(79, '2022-02-23', 3, 51),
	(57, '2020-08-26', 5, 32),
	(2, '2022-09-05', 4, 85),
	(94, '2021-07-10', 2, 89),
	(31, '2017-01-28', 5, 48),
	(88, '2022-07-21', 2, 84),
	(79, '2019-10-14', 1, 72),
	(35, '2022-01-08', 1, 73),
	(41, '2022-01-11', 1, 75),
	(18, '2021-08-21', 3, 69),
	(91, '2019-11-13', 2, 49),
	(90, '2017-06-10', 2, 9),
	(81, '2018-11-09', 4, 47),
	(21, '2017-07-14', 3, 30),
	(37, '2017-03-23', 2, 23),
	(99, '2017-02-10', 4, 88),
	(61, '2018-04-22', 4, 5),
	(83, '2017-04-12', 1, 41),
	(47, '2016-04-05', 5, 80),
	(51, '2015-01-26', 5, 13),
	(70, '2016-04-04', 3, 23),
	(78, '2021-08-15', 5, 54),
	(42, '2021-03-02', 2, 7),
	(90, '2022-08-16', 4, 70),
	(74, '2020-08-02', 5, 70),
	(26, '2022-04-03', 2, 17),
	(22, '2020-11-10', 5, 20),
	(100, '2020-03-27', 4, 62),
	(38, '2022-10-18', 1, 54),
	(99, '2015-08-02', 5, 1),
	(75, '2016-09-25', 5, 67),
	(54, '2018-02-27', 5, 70),
	(29, '2017-04-06', 1, 6),
	(65, '2022-09-28', 3, 82),
	(88, '2015-03-07', 1, 7),
	(18, '2021-11-01', 2, 73),
	(60, '2022-10-06', 4, 28),
	(32, '2015-08-10', 2, 78),
	(93, '2022-02-10', 4, 8),
	(51, '2016-03-01', 1, 21),
	(74, '2015-07-14', 2, 21),
	(32, '2016-07-10', 4, 13),
	(27, '2019-03-15', 3, 57),
	(15, '2015-12-11', 2, 57),
	(74, '2017-08-01', 2, 11),
	(20, '2021-11-03', 2, 10),
	(89, '2015-08-24', 3, 52),
	(71, '2020-12-18', 3, 33),
	(67, '2019-05-12', 5, 19),
	(49, '2021-07-01', 3, 8),
	(52, '2020-07-11', 4, 61),
	(21, '2021-08-15', 2, 31),
	(83, '2021-03-01', 5, 13),
	(41, '2020-09-19', 2, 5),
	(6, '2018-11-28', 1, 11),
	(52, '2018-03-13', 3, 8),
	(4, '2022-08-17', 3, 70),
	(83, '2019-03-16', 3, 63),
	(35, '2015-11-09', 2, 47),
	(23, '2018-03-08', 3, 51),
	(4, '2020-04-24', 5, 76),
	(24, '2019-11-13', 1, 2),
	(5, '2020-01-15', 1, 63),
	(93, '2021-11-21', 4, 78),
	(16, '2018-11-03', 2, 66),
	(93, '2019-02-16', 1, 94),
	(56, '2022-08-13', 1, 27),
	(21, '2016-11-09', 3, 46),
	(54, '2020-04-11', 5, 60),
	(35, '2018-01-28', 3, 27),
	(44, '2015-11-16', 5, 98),
	(12, '2019-10-03', 3, 18),
	(8, '2019-10-17', 3, 0),
	(33, '2015-02-05', 3, 71),
	(96, '2021-08-21', 3, 52),
	(92, '2020-07-03', 3, 14),
	(93, '2015-01-04', 2, 9),
	(17, '2017-07-18', 5, 84),
	(16, '2017-08-23', 3, 82),
	(27, '2022-01-16', 2, 74),
	(12, '2015-02-03', 1, 57),
	(99, '2019-01-06', 5, 74),
	(63, '2015-10-28', 4, 18),
	(79, '2016-08-09', 5, 9),
	(21, '2022-04-04', 2, 11),
	(34, '2020-12-28', 5, 27),
	(97, '2015-12-17', 5, 47),
	(35, '2022-11-04', 1, 62),
	(53, '2018-07-25', 3, 20),
	(93, '2018-04-06', 2, 100),
	(92, '2022-11-07', 3, 42),
	(21, '2017-02-26', 4, 40),
	(40, '2022-12-17', 4, 22),
	(47, '2021-02-12', 2, 73),
	(8, '2020-04-21', 5, 7),
	(40, '2017-08-08', 3, 40),
	(51, '2015-08-07', 5, 56),
	(90, '2018-08-28', 4, 8),
	(79, '2022-06-24', 3, 43),
	(50, '2015-09-21', 5, 12),
	(86, '2018-12-17', 2, 20),
	(1, '2019-11-24', 1, 2),
	(50, '2018-01-20', 1, 60),
	(44, '2019-06-26', 5, 50),
	(70, '2019-11-16', 3, 86),
	(54, '2015-10-01', 4, 26),
	(9, '2021-06-19', 2, 70),
	(36, '2019-05-16', 5, 41),
	(57, '2022-12-26', 2, 51),
	(1, '2019-09-28', 1, 59),
	(49, '2022-06-20', 2, 52),
	(61, '2016-02-07', 2, 27),
	(88, '2018-06-28', 2, 96),
	(47, '2022-02-28', 3, 2),
	(90, '2019-05-07', 3, 53),
	(20, '2022-05-20', 5, 42),
	(78, '2015-05-21', 1, 93),
	(61, '2020-06-14', 5, 94),
	(82, '2015-02-22', 1, 50),
	(47, '2021-03-04', 3, 8),
	(11, '2015-11-12', 4, 93),
	(0, '2015-02-03', 1, 61),
	(96, '2018-05-10', 3, 75),
	(64, '2022-06-22', 3, 45),
	(28, '2016-12-07', 1, 75),
	(73, '2020-12-10', 5, 43),
	(92, '2015-09-08', 5, 26),
	(93, '2016-01-21', 2, 47),
	(3, '2021-02-19', 3, 36),
	(17, '2022-04-22', 1, 36),
	(35, '2018-12-01', 4, 23),
	(34, '2015-01-24', 5, 45),
	(93, '2019-06-22', 5, 71),
	(29, '2020-12-12', 3, 20),
	(92, '2015-03-06', 5, 79),
	(62, '2015-04-17', 4, 75),
	(99, '2016-05-26', 1, 83),
	(41, '2019-01-01', 1, 50),
	(99, '2018-05-21', 4, 20),
	(58, '2015-09-28', 5, 98),
	(97, '2021-02-12', 1, 11),
	(52, '2020-07-21', 5, 43),
	(97, '2019-06-27', 2, 11);

INSERT INTO blood_donation (EmployeeId, DonorId, ScreenResult, DonationDate, Amount) VALUES
	(96, 23, 'negative', '2017-11-08', 47),
	(89, 9, 'positive', '2017-07-27', 40),
	(12, 50, 'positive', '2016-12-23', 94),
	(6, 39, 'positive', '2015-04-27', 16),
	(76, 83, 'positive', '2016-07-19', 9),
	(87, 43, 'positive', '2015-01-28', 89),
	(97, 15, 'negative', '2022-03-02', 62),
	(10, 33, 'positive', '2017-10-04', 40),
	(81, 29, 'positive', '2016-01-01', 84),
	(64, 40, 'negative', '2016-02-21', 14),
	(70, 42, 'negative', '2019-05-04', 65),
	(77, 50, 'positive', '2020-02-14', 55),
	(66, 59, 'negative', '2018-03-11', 24),
	(56, 56, 'positive', '2016-07-04', 32),
	(35, 72, 'negative', '2017-12-18', 57),
	(64, 38, 'negative', '2021-04-19', 89),
	(62, 85, 'positive', '2022-01-18', 6),
	(98, 83, 'positive', '2015-03-14', 27),
	(40, 48, 'negative', '2019-12-13', 15),
	(42, 69, 'negative', '2016-07-05', 18),
	(30, 68, 'negative', '2016-03-03', 87),
	(8, 95, 'positive', '2015-07-19', 94),
	(45, 94, 'positive', '2022-02-09', 22),
	(61, 31, 'positive', '2018-06-05', 85),
	(66, 34, 'negative', '2015-08-02', 31),
	(20, 25, 'positive', '2022-11-10', 56),
	(11, 56, 'negative', '2016-09-13', 23),
	(58, 83, 'positive', '2020-06-24', 59),
	(41, 74, 'positive', '2019-05-15', 57),
	(26, 63, 'positive', '2015-05-20', 10),
	(28, 57, 'positive', '2022-04-10', 68),
	(80, 10, 'negative', '2016-03-01', 3),
	(33, 29, 'negative', '2018-11-17', 54),
	(36, 35, 'positive', '2019-01-02', 65),
	(53, 58, 'negative', '2016-02-04', 5),
	(18, 1, 'negative', '2017-04-12', 67),
	(74, 50, 'positive', '2015-04-28', 66),
	(19, 25, 'positive', '2020-07-07', 40),
	(70, 89, 'negative', '2015-02-09', 86),
	(49, 89, 'negative', '2021-07-11', 30),
	(73, 94, 'negative', '2016-03-08', 86),
	(62, 84, 'positive', '2019-10-27', 23),
	(12, 88, 'positive', '2019-09-12', 87),
	(16, 26, 'positive', '2018-06-03', 81),
	(20, 49, 'negative', '2017-06-06', 89),
	(18, 10, 'positive', '2021-03-23', 62),
	(26, 80, 'positive', '2021-11-10', 17),
	(74, 45, 'positive', '2016-12-05', 9),
	(37, 85, 'negative', '2018-08-20', 100),
	(78, 22, 'negative', '2016-03-12', 66),
	(75, 92, 'positive', '2019-03-25', 40),
	(26, 52, 'negative', '2016-04-01', 47),
	(2, 9, 'positive', '2021-03-24', 59),
	(65, 46, 'negative', '2021-01-06', 97),
	(18, 0, 'positive', '2018-10-04', 14),
	(38, 21, 'positive', '2017-03-20', 89),
	(38, 82, 'positive', '2022-05-17', 86),
	(9, 44, 'negative', '2019-12-24', 18),
	(92, 38, 'positive', '2019-11-15', 62),
	(81, 57, 'positive', '2017-05-23', 39),
	(90, 68, 'positive', '2020-08-08', 86),
	(98, 85, 'negative', '2016-04-18', 78),
	(85, 4, 'negative', '2015-08-18', 48),
	(35, 4, 'positive', '2021-09-02', 37),
	(6, 30, 'positive', '2021-03-26', 1),
	(7, 64, 'negative', '2019-10-14', 20),
	(98, 85, 'positive', '2022-05-08', 18),
	(63, 55, 'positive', '2017-09-12', 23),
	(46, 40, 'negative', '2015-08-08', 75),
	(29, 57, 'negative', '2021-07-20', 92),
	(78, 10, 'positive', '2016-08-09', 67),
	(3, 33, 'negative', '2020-03-09', 40),
	(87, 76, 'negative', '2021-11-10', 35),
	(73, 23, 'positive', '2017-07-18', 1),
	(46, 66, 'negative', '2016-08-26', 0),
	(12, 7, 'negative', '2016-10-24', 96),
	(54, 0, 'negative', '2016-09-13', 21),
	(31, 97, 'negative', '2018-02-27', 18),
	(15, 100, 'positive', '2022-07-12', 43),
	(88, 25, 'positive', '2022-09-28', 29),
	(16, 30, 'negative', '2020-06-03', 72),
	(32, 13, 'negative', '2019-06-01', 39),
	(45, 43, 'negative', '2020-06-20', 4),
	(12, 49, 'negative', '2017-03-07', 95),
	(6, 19, 'negative', '2019-05-09', 36),
	(2, 43, 'negative', '2021-02-21', 88),
	(43, 10, 'negative', '2021-05-19', 47),
	(35, 31, 'negative', '2020-02-28', 70),
	(95, 90, 'negative', '2019-06-25', 83),
	(76, 93, 'positive', '2022-03-15', 71),
	(82, 80, 'negative', '2019-11-03', 52),
	(65, 2, 'negative', '2020-04-24', 25),
	(70, 100, 'negative', '2022-05-25', 36),
	(86, 24, 'negative', '2015-01-20', 24),
	(79, 28, 'negative', '2021-05-05', 23),
	(94, 100, 'negative', '2020-05-08', 61),
	(60, 44, 'positive', '2022-11-28', 100),
	(98, 81, 'negative', '2016-04-14', 52),
	(29, 97, 'positive', '2018-09-22', 32),
	(1, 16, 'negative', '2018-07-24', 88),
	(98, 91, 'negative', '2020-04-11', 70),
	(18, 7, 'positive', '2022-06-08', 76),
	(80, 57, 'positive', '2022-06-22', 10),
	(39, 43, 'negative', '2017-11-01', 20),
	(21, 87, 'negative', '2021-12-12', 87),
	(68, 35, 'negative', '2017-04-07', 40),
	(39, 59, 'negative', '2021-01-21', 88),
	(55, 57, 'positive', '2022-06-25', 47),
	(17, 64, 'positive', '2015-04-08', 72),
	(12, 43, 'negative', '2020-02-17', 62),
	(52, 1, 'positive', '2021-11-15', 48),
	(1, 58, 'positive', '2018-09-15', 67),
	(55, 16, 'negative', '2019-12-04', 65),
	(7, 2, 'negative', '2022-10-07', 88),
	(78, 41, 'positive', '2018-06-28', 91),
	(64, 56, 'positive', '2022-11-19', 48),
	(60, 15, 'negative', '2017-04-13', 86),
	(29, 33, 'negative', '2021-03-12', 69),
	(33, 13, 'positive', '2020-02-23', 25),
	(67, 100, 'positive', '2018-08-25', 36),
	(11, 87, 'negative', '2015-09-05', 40),
	(80, 92, 'positive', '2021-01-28', 95),
	(22, 9, 'positive', '2015-09-10', 58),
	(94, 11, 'positive', '2021-06-22', 16),
	(91, 52, 'negative', '2015-09-14', 16),
	(64, 29, 'negative', '2017-08-02', 50),
	(49, 76, 'positive', '2018-05-13', 5),
	(80, 37, 'negative', '2019-05-02', 70),
	(89, 18, 'positive', '2019-03-05', 52),
	(62, 97, 'negative', '2018-04-09', 5),
	(69, 32, 'positive', '2021-10-14', 38),
	(2, 23, 'positive', '2015-08-06', 4),
	(96, 67, 'negative', '2015-10-10', 26),
	(79, 29, 'negative', '2020-06-04', 65),
	(19, 22, 'negative', '2021-05-25', 5),
	(17, 29, 'positive', '2017-03-03', 58),
	(46, 68, 'positive', '2020-03-05', 16),
	(44, 26, 'negative', '2022-12-16', 10),
	(40, 23, 'positive', '2018-06-15', 5),
	(96, 23, 'negative', '2022-01-01', 27),
	(79, 60, 'negative', '2020-04-08', 47),
	(31, 67, 'positive', '2015-03-26', 87),
	(94, 26, 'negative', '2020-08-04', 26),
	(78, 19, 'positive', '2016-07-25', 99),
	(85, 21, 'positive', '2016-02-24', 83),
	(59, 53, 'positive', '2017-06-10', 43),
	(6, 81, 'negative', '2021-05-05', 11),
	(99, 1, 'positive', '2017-05-17', 13),
	(44, 45, 'negative', '2020-08-16', 38),
	(42, 97, 'positive', '2018-11-16', 59),
	(75, 96, 'positive', '2018-06-10', 58),
	(3, 2, 'positive', '2018-02-04', 93),
	(60, 61, 'negative', '2017-08-07', 96),
	(22, 73, 'negative', '2022-02-22', 72),
	(14, 77, 'positive', '2018-05-04', 25),
	(28, 38, 'negative', '2019-05-13', 9),
	(17, 76, 'negative', '2016-08-09', 81),
	(29, 46, 'negative', '2018-08-13', 76),
	(19, 72, 'positive', '2016-09-02', 80),
	(72, 27, 'negative', '2022-03-22', 87),
	(14, 92, 'positive', '2022-08-09', 52),
	(41, 69, 'negative', '2021-01-15', 76),
	(87, 90, 'positive', '2019-08-23', 67),
	(30, 96, 'negative', '2021-03-25', 39),
	(62, 26, 'positive', '2016-07-07', 99),
	(65, 82, 'negative', '2019-02-24', 50),
	(77, 54, 'negative', '2018-02-05', 16),
	(69, 81, 'negative', '2015-02-19', 58),
	(60, 29, 'positive', '2022-10-06', 42),
	(43, 26, 'negative', '2017-10-10', 38),
	(8, 84, 'positive', '2017-10-03', 88),
	(63, 14, 'negative', '2019-07-27', 34),
	(15, 82, 'negative', '2018-10-24', 34),
	(5, 53, 'positive', '2015-09-25', 25),
	(26, 20, 'positive', '2015-09-19', 27),
	(30, 8, 'positive', '2019-03-04', 34),
	(22, 33, 'negative', '2021-11-13', 15),
	(87, 46, 'negative', '2016-02-25', 74),
	(73, 53, 'negative', '2015-03-06', 61),
	(95, 0, 'negative', '2015-10-21', 6),
	(65, 38, 'positive', '2019-07-14', 2),
	(68, 91, 'negative', '2017-05-19', 92),
	(60, 22, 'negative', '2022-04-06', 73),
	(26, 24, 'positive', '2019-08-17', 52),
	(2, 67, 'positive', '2017-12-26', 5),
	(42, 7, 'negative', '2020-04-25', 92),
	(5, 66, 'negative', '2020-09-19', 30),
	(1, 36, 'negative', '2017-11-28', 43),
	(77, 1, 'positive', '2015-11-11', 59),
	(96, 28, 'negative', '2017-05-28', 51),
	(58, 83, 'negative', '2022-05-02', 24),
	(61, 9, 'negative', '2020-05-19', 58),
	(35, 80, 'negative', '2022-08-26', 8),
	(35, 3, 'negative', '2020-05-19', 4),
	(12, 44, 'negative', '2015-03-16', 89),
	(52, 28, 'positive', '2021-07-05', 19),
	(29, 20, 'positive', '2015-08-22', 91),
	(38, 76, 'positive', '2016-10-21', 57),
	(99, 9, 'negative', '2022-10-24', 61),
	(63, 60, 'negative', '2021-11-17', 14);

-- Add the foreign key constraints using a single transaction

USE bloodbank;

START TRANSACTION;
SET FOREIGN_KEY_CHECKS=0; 

ALTER TABLE blood_bank_employee
ADD CONSTRAINT fk_employee_blood_bank_id FOREIGN KEY (EmployerId)
REFERENCES blood_bank(BloodBankId) ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE hospital_employee
ADD CONSTRAINT fk_employee_hospital_id FOREIGN KEY (EmployerId)
REFERENCES hospital(HospitalId) ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE blood_transfusion
ADD CONSTRAINT fk_transfusion_employee_id FOREIGN KEY (EmployeeId)
REFERENCES hospital_employee(EmployeeId) ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE blood_transfusion
ADD CONSTRAINT fk_transfusion_recipient_id FOREIGN KEY (RecipientId)
REFERENCES client(ClientId) ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE blood_donation
ADD CONSTRAINT fk_donation_employee_id FOREIGN KEY (EmployeeId)
REFERENCES blood_bank_employee(EmployeeId) ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE blood_donation
ADD CONSTRAINT fk_donation_donor_id FOREIGN KEY (DonorId)
REFERENCES client(ClientId) ON DELETE RESTRICT
ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS=1;
COMMIT;
